name = "speedmath"
compatibility_date = "2026-07-10"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "d1-synapse"
database_id = "3fedf6c0-7445-4a28-8a2d-c5f15f668b2c"
